version: "3"
services:
  db:
    container_name: wumo-db
    image: mysql
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always

  redis:
    container_name: redis_boot
    image: redis:alpine
    env_file:
      - spring.env
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"